spring.application.name=ProgrammingAlgorithms
server.port=8085

# Configuración directa de PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d8b4s75ckfvc73cmep20-a.ohio-postgres.render.com:5432/progra_db
spring.datasource.username=progra_db_user
spring.datasource.password=m2FEdypr8drF4JARQIUOKeoH1oBydiv9
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
