spring.application.name=ProgrammingAlgorithms

# Render inyectará el PORT automáticamente, si no existe, usa 8085
server.port=${PORT:8085}

# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS POSTGRESQL
# ==========================================

# Usamos las variables de entorno de Render (con valores por defecto para tu desarrollo local)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5445/postgres?serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:aloha123}

spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ==========================================
# HHH90000025: No hace falta especificar el dialecto, Hibernate lo detecta solo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
