spring.application.name=ProgrammingAlgorithms

server.port=${PORT:8085}

# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS POSTGRESQL
# ==========================================

# 1. Apuntamos a la base de datos por defecto 'postgres'
spring.datasource.url=jdbc:postgresql://localhost:5445/postgres?serverTimezone=UTC

# 2. Credenciales (Corregida la contraseña a minúsculas)
spring.datasource.username=postgres
spring.datasource.password=aloha123




spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true